/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { GnosisSafeProxy } from "./GnosisSafeProxy";

export class GnosisSafeProxyFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(_singleton: string, overrides?: Overrides): Promise<GnosisSafeProxy> {
    return super.deploy(
      _singleton,
      overrides || {}
    ) as Promise<GnosisSafeProxy>;
  }
  getDeployTransaction(
    _singleton: string,
    overrides?: Overrides
  ): TransactionRequest {
    return super.getDeployTransaction(_singleton, overrides || {});
  }
  attach(address: string): GnosisSafeProxy {
    return super.attach(address) as GnosisSafeProxy;
  }
  connect(signer: Signer): GnosisSafeProxyFactory {
    return super.connect(signer) as GnosisSafeProxyFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GnosisSafeProxy {
    return new Contract(address, _abi, signerOrProvider) as GnosisSafeProxy;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_singleton",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516101473803806101478339818101604052602081101561003357600080fd5b50516001600160a01b03811661007a5760405162461bcd60e51b81526004018080602001828103825260228152602001806101256022913960400191505060405180910390fd5b600080546001600160a01b039092166001600160a01b0319909216919091179055607c806100a96000396000f3fe6080604052600080546001600160a01b0316813563530ca43760e11b1415602857808252602082f35b3682833781823684845af490503d82833e806041573d82fd5b503d81f3fea2646970667358221220f04634abc6b80c8666c923842ed5d9a63dddbb317bb246442a00397b050b065164736f6c63430007060033496e76616c69642073696e676c65746f6e20616464726573732070726f7669646564";
