/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface GuildFactoryInterface extends ethers.utils.Interface {
  functions: {
    "createGuild(bytes)": FunctionFragment;
    "guildsOf(address)": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "predictDeterministicAddress(bytes32)": FunctionFragment;
    "template()": FunctionFragment;
    "totalGuilds()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createGuild",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "guildsOf", values: [string]): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(
    functionFragment: "predictDeterministicAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "template", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalGuilds",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createGuild",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "guildsOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "predictDeterministicAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "template", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalGuilds",
    data: BytesLike
  ): Result;

  events: {
    "NewGuild(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewGuild"): EventFragment;
}

export class GuildFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: GuildFactoryInterface;

  functions: {
    "createGuild(bytes)"(
      _initData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createGuild(bytes,bytes32)"(
      _initData: BytesLike,
      _salt: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    guildsOf(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
    }>;

    "guildsOf(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
    }>;

    initialize(
      _template: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address)"(
      _template: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    predictDeterministicAddress(
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      predicted: string;
      0: string;
    }>;

    "predictDeterministicAddress(bytes32)"(
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      predicted: string;
      0: string;
    }>;

    template(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "template()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    totalGuilds(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "totalGuilds()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;
  };

  "createGuild(bytes)"(
    _initData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createGuild(bytes,bytes32)"(
    _initData: BytesLike,
    _salt: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  guildsOf(_owner: string, overrides?: CallOverrides): Promise<string[]>;

  "guildsOf(address)"(
    _owner: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  initialize(
    _template: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address)"(
    _template: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  predictDeterministicAddress(
    _salt: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "predictDeterministicAddress(bytes32)"(
    _salt: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  template(overrides?: CallOverrides): Promise<string>;

  "template()"(overrides?: CallOverrides): Promise<string>;

  totalGuilds(overrides?: CallOverrides): Promise<BigNumber>;

  "totalGuilds()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    "createGuild(bytes)"(
      _initData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "createGuild(bytes,bytes32)"(
      _initData: BytesLike,
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    guildsOf(_owner: string, overrides?: CallOverrides): Promise<string[]>;

    "guildsOf(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    initialize(_template: string, overrides?: CallOverrides): Promise<void>;

    "initialize(address)"(
      _template: string,
      overrides?: CallOverrides
    ): Promise<void>;

    predictDeterministicAddress(
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "predictDeterministicAddress(bytes32)"(
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    template(overrides?: CallOverrides): Promise<string>;

    "template()"(overrides?: CallOverrides): Promise<string>;

    totalGuilds(overrides?: CallOverrides): Promise<BigNumber>;

    "totalGuilds()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    NewGuild(guildOwner: string | null, guild: string | null): EventFilter;
  };

  estimateGas: {
    "createGuild(bytes)"(
      _initData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createGuild(bytes,bytes32)"(
      _initData: BytesLike,
      _salt: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    guildsOf(_owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    "guildsOf(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(_template: string, overrides?: Overrides): Promise<BigNumber>;

    "initialize(address)"(
      _template: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    predictDeterministicAddress(
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "predictDeterministicAddress(bytes32)"(
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    template(overrides?: CallOverrides): Promise<BigNumber>;

    "template()"(overrides?: CallOverrides): Promise<BigNumber>;

    totalGuilds(overrides?: CallOverrides): Promise<BigNumber>;

    "totalGuilds()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    "createGuild(bytes)"(
      _initData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createGuild(bytes,bytes32)"(
      _initData: BytesLike,
      _salt: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    guildsOf(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "guildsOf(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _template: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address)"(
      _template: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    predictDeterministicAddress(
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "predictDeterministicAddress(bytes32)"(
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    template(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "template()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalGuilds(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "totalGuilds()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
